config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  put '/tasks', to: 'tasks#complete', as: 'task_complete'
  get '/tasks/calendar', to: 'tasks#calendar'

  resources :tasks
  resources :tags
  resource :labelleds,  except: [ :update]
  resources :labelleds,  only: [:edit, :update] #se crea un bug al renderizar el form para actualizar el labelled(asingnacion de etiqueta y tarea) solicita labelleds_path y no labelled_path, :S
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/labelled.rb
class Labelled < ApplicationRecord
  belongs_to :task
  belongs_to :tag, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :labelleds, dependent: :destroy

  belongs_to :user
  validates :title, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :title, presence: true , uniqueness: true
  validates :importance, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  has_many :labelleds, dependent: :destroy
  # has_many :tags, :length => { :maximum => 3 }
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks, dependent: :destroy
  has_many :tags, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/labelleds_controller.rb
require 'byebug'
class LabelledsController < ApplicationController
  def edit
    @tags = Tag.where(user_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def update
    # byebug
    @labelleld = Labelled.find(params[:id])
    respond_to do |format|
      if @labelleld.update(set_labelled)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @labelleld.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  private
  def set_labelled
    params.require(:labelled1).permit(:tag_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tags_controller.rb
require 'byebug'

class TagsController < ApplicationController
  protect_from_forgery except: :new
  before_action :set_tag, only: [:edit, :update, :destroy]


  def index
    @tags = Tag.where(user_id: current_user.id)
  end

  def new
    @tag = Tag.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    respond_to do |format|
      if @tag.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @tag.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @tag.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:title, :color)
  end

  def set_tag
      @tag = Tag.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
require 'byebug'

class TasksController < ApplicationController
    protect_from_forgery except: :new
  before_action :set_task, only: [:edit, :update, :destroy]


  def index


    if (params["/tasks"]  )
      # @tasks = Labelled.joins(:task).where(tag_id: params["/tasks"]["tag_id"] )
      @task_name = params["/tasks"]["task_name"]
      @importace = params["/tasks"]["importance"]
      @start_date = params["/tasks"]["start_date"]
      @end_date = params["/tasks"]["end_date"]
      @tag_id = params["/tasks"]["tag_id"]
      @tasks_all = search_tasks(current_user,@task_name,@tag_id,@importace,@start_date,@end_date )
      @tasks = @tasks_all.where(state: false)
      @tasks_completed = @tasks_all.where(state: true)
    elsif (params[:tag_id])
      @tasks = Task.where(user_id: current_user.id).order(:start_date).where(state: false).joins(:labelleds).where( 'labelleds.tag_id' => params[:tag_id])
      @tasks_completed = Task.where(user_id: current_user.id).order(:start_date).where(state: true).joins(:labelleds).where( 'labelleds.tag_id' => params[:tag_id])
    else
      @tasks_completed = Task.where(user_id: current_user.id).order(:start_date).where(state: true)

      @tasks = Task.where(user_id: current_user.id).order(:start_date).where(state: false)
    end

  end

  def calendar
    index

  end

  def show
  end

  def new
    @task = Task.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user


    respond_to do |format|
      if @task.save
        Labelled.create(task_id: @task.id)
        Labelled.create(task_id: @task.id)
        Labelled.create(task_id: @task.id)
        format.js
      else
        format.json { render json: @task.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @task.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def complete
    #.toggle!(:active)
    @task = Task.find(params[:task_id])
    if @task.state
      @task.state = false
    else
      @task.state = true
    end
    @task.save
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def task_params

    params.require(:task).permit(:title, :description, :importance, :start_date, :end_date)
  end

  def set_task
      @task = Task.find(params[:id])
  end

  def search_tasks(usuario,task_name,tag_id,importace,start_date,end_date ) # metodo solicitado
    @tasks = usuario.tasks
          # @task_user = current_user.tasks
    @task_task_name = @tasks.where("title ILIKE ?", "%#{task_name}%")

    @task_importance = @task_task_name.where(importance: importace)
    @task_importance = @task_task_name if @task_importance.size == 0

    @task_start_date = @task_importance.where(start_date: "#{start_date} 00:00:00.000000000 +0000")
    @task_start_date = @task_importance if @task_start_date.size == 0

    @task_end_date = @task_start_date.where(end_date: "#{end_date} 00:00:00.000000000 +0000")
    @task_end_date = @task_start_date if @task_end_date.size == 0
    @tasks = @task_end_date
    @tasks = @tasks.joins(:labelleds).where( 'labelleds.tag_id' => tag_id)
    @tasks = @task_end_date if @tasks.size == 0
    return @tasks.order(:start_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="https://assets.ifttt.com/images/channels/1148373811/icons/large.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# Adding fonts  %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@100;300;500;700&family=Bellefair&family=Inter:wght@300;500;700;900&family=Poppins:wght@900&family=Roboto:wght@100;300;500;700;900&display=swap" rel="stylesheet">
      </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Colored scrolling</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-block">
        <div>
          <a href="<%= tasks_path %>" > Mis tareas <button> <i class="fa-solid fa-list-check"></i> </button> </a>
        </div>
        <div>
          <a href="<%= tags_path %>"> Mis Etiquetas <button><i class="fa-solid fa-tag"></i></i></button> </a>
        </div>
        <div>
          <a href="<%= tasks_calendar_path %>"> Calendario <button><i class="fa-solid fa-tag"></i></i></button> </a>
        </div>

      </div>
    </div>

    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Backdrop with scrolling</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <p>Try scrolling the rest of the page to see this option in action.</p>
      </div>
    </div>
    <div style="margin-left: 250px">
     <%= yield %>
     <%= render "tasks/modal_task"%>
     <%= render "tags/modal_tag"%>
     <%= render "labelleds/modal_labelled"%>

    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/26ac38895c.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/index.html.erb
<h1 id="h1">mis tareasmis tareasmis tareasmis tareasmis tareasmis tareasmis tareasmis tareasmis tareas</h1>

<%= link_to "raa",new_task_path, {remote: true, class: "btn btn-info", id: "anadir-categoria-btn"}  %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tags/create.js.erb
$('#modaltag').modal('toggle');
$('#tags-lists').append(
    '<div class="row"><div class="col-1"><a ><i class="fa-solid fa-tag"></i></a></div><div class="col-7"><span> <%= @tag.title%> </span></div><div class="col-3"><%= link_to edit_tag_path(@tag), html_options = {class: "btn  btn-xs", remote: true} do %><i class="fa-solid fa-pen-to-square"></i><% end %><%= link_to @tag , remote: true, method: :delete, data: { confirm: "¿Estas seguro de borrar la Etiqueta:: #{tag.title}?"}, class: "btn btn-xs" do %><i class="fa-solid fa-trash-can"></i> <% end %></div></div>'
);

app/views/tags/destroy.js.erb
$('#tag-<%= @tag.id %>').fadeOut();

app/views/tasks/calendar.html.erb
<br>
  <% @today = Time.zone.now%>
  <h3>Today: <%= @today.strftime('%d %A %b')%></h3>
<div class="container calendar-tasks">
  <ul id="tasks-lists">
    <li id="task-id">
      <div class="row">
      <div class="col-1">
        <a >
          Inicio
        </a>
      </div>
      <div class="col-1">
        <a >
          Fin
        </a>
      </div>
      <div class="col-1">
        <a >
          Terminar
        </a>
      </div>
      <div class="col-1">
        <a >
          Importancia
        </a>
      </div>
      <div class="col-3">
        <span> Titulo</span>
      </div>
      <div class="col-3 d-flex justify-content-center">
        Etiquetas
      </div>
      <div class="col-2">

        <span>Editar/Eliminar</span>
      </div>
      </div>
    </li>
    <%7.times do%>
      <p><%= @today.strftime('%d %A %b')%></p>
      <% @tasks.each do |task|%>
       <% if task.start_date <=@today &&  task.end_date >= @today%>
        <li id="task-<%=task.id%>" class="task-iterated">
    <div class="row">
     <div class="col-1 text-date ">
      <span> <%=task.start_date.to_s.to_date%> </span>
     </div>
     <div class="col-1 text-date">
      <span> <%=task.end_date.to_s.to_date %> </span>
     </div>
     <div class="col-1 mark-complete d-flex justify-content-center">
      <%= link_to  task_complete_path(task_id: task.id),remote: true,method: :put, data: { confirm: "¿Estas seguro de Completar la Tarea:a: #{task.title}?"} do %>
                  <i class="fa-solid fa-check" data-complete-task="<%=task.id%>"></i>
                <% end %>
     </div>
     <div class="col-1 importance d-flex justify-content-center">
      <span> <%=task.importance%> </span>
    </div>
     <div class="col-3">
      <span> <%= task.title%> </span>
     </div>
     <div class="col-3 col-de-etiquetas" style="font-size:10px; font-weigth:700;">
       <div class="row">
        <div class="col-3" style="background-color:<%=task.labelleds.first.tag.present? ? task.labelleds.first.tag.color : "gray"%>; height:16px">
          <%# Refactorizar1 %>
          <%if task.labelleds.first.tag_id.present? && task.labelleds.first.tag.title.present? %>
            <%= link_to "#{task.labelleds.first.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.second.tag.present? ? task.labelleds.second.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.second.tag_id.present?%>
            <%= link_to "#{task.labelleds.second.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.third.tag.present? ? task.labelleds.third.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.third.tag_id.present?%>
            <%= link_to "#{task.labelleds.third.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3">
          <% label = task.labelleds.third%>
            <%= link_to  edit_labelleds_path(task_id: task.id), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-tags" data-task="<%=task.id%>" ></i>
                <% end %>
        </div>
       </div>
     </div>
     <div class="col-2">
      <%= link_to edit_task_path(task), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
      <%= link_to task, remote: true, method: :delete, data: { confirm: "¿Estas segurode borrar la Tarea: #{task.title}?"}, class: "btn btn-xs"  do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
     </div>

    </div>
  </li>
       <% end %>
      <%end%>
    <% @today=@today +1.day %>
    <% end%>
  </ul>
</div>

app/views/tasks/index.html.erb
<div class="row d-flex w-75 search-bar mt-4 mb-4">
  <% form_tag tasks_path, method: :get,class:"d-flex" do %>
    <div class="row">
      <div class="col-2">
        <%= label_tag(:task_name, "Tarea:") %>
        <%= text_field_tag :task_name,
          params[:task_name],
          class: "form-control",
          placeholder: "Hacer..."
        %>
      </div>

      <div class="col-2">
        <%= label_tag(:tag_id, "Etiquetas:") %>
        <%= select_tag(:tag, options_from_collection_for_select(Tag.all, :id, :title), class: "form-control",placeholder: "Etiquetas")%>
      </div>

      <div class="col-2">
        <%= label_tag(:state, "Estado:") %>
        <%= select_tag(:state, options_for_select([ 'No Especificado','Pendiente','Terminado' ]), class: "form-control",placeholder: "Estado")%>
      </div>

      <div class="col-2">
        <%= label_tag(:importt, "Importancia:") %>
        <%= select_tag(:importt, options_for_select([ 'No Especificado','uno','dos','tres','cuatro','cinco' ]), class: "form-control",placeholder: "Estado")%>
      </div>



      <div class="col-2">
        <%= label_tag(:start_date, "Fecha ini:") %>
        <%= date_field_tag(:start_date, Date.today)%>
      </div>

      <div class="col-2">
        <%= label_tag(:end_date, "Fecha fin:") %>
        <%= date_field_tag :end_date,
          params[:end_date],
          class: "form-control",
          placeholder: "12/23/2082"
        %>
      </div>

    </div>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <% @STATUS = ["No Especficiado",1,2,3,4,5]%>
  <%= form_for tasks_path, method: :get,class:"d-flex" do |f| %>
  <div class="row">
    <div class=col-2>
      <%= f.label :task_name, "Tarea" %>
      <%= f.text_field :task_name %>
    </div>
    <div class="col-2">
      <%= f.label :importance, "Importancia" %>
      <%= f.select :importance, @STATUS %>
    </div>
    <div class="col-2">
      <%= f.label :tag_id, "Etiquetas disponibles" %>
      <%= f.collection_select :tag_id, Tag.where(user_id: current_user.id),:id,:title, include_blank: true %>
    </div>
    <div class="col-2">
      <%= f.label :start_date, "Fecha inicio" %>
      <%= f.date_field :start_date %>
    </div>
    <div class="col-2">
      <%= f.label :end_date, "Fecha fim" %>
      <%= f.date_field :end_date %><br />
    </div>
    <div class="col-2">
      <%= f.submit "Search"%>
    </div>
  </div>
<% end %>

</div>

<div class="row container">
  <div class="col">
    <h3>Mis Tareas Pendientes</h3>
  </div>

  <div class="col">
    <%= link_to  new_task_path ,{remote: true, class: "btn btn-add-tag", id: "anadir-categoria-btn"} do %>
       Crear Tarea <i class="fa-solid fa-plus"></i>
      <% end %>
  </div>

</div>

<div class="container list-tasks">
  <ul id="tasks-lists" class="tasks-list-ToDo">
    <li id="task-id">
      <div class="row">
      <div class="col-1">
        <a >
          Inicio
        </a>
      </div>
      <div class="col-1">
        <a >
          Fin
        </a>
      </div>
      <div class="col-1">
        <a >
          Terminar
        </a>
      </div>
      <div class="col-1">
        <a >
          Importancia
        </a>
      </div>
      <div class="col-3">
        <span> Titulo</span>
      </div>
      <div class="col-3">
        Etiquetas
      </div>
      <div class="col-2">

        <span>Editar/Eliminar</span>
      </div>
      </div>
    </li>
  <%@tasks.each do |task|%>
  <li id="task-<%=task.id%>" class="task-iterated">
    <div class="row">
     <div class="col-1 text-date ">
      <span> <%=task.start_date.to_s.to_date%> </span>
     </div>
     <div class="col-1 text-date">
      <span> <%=task.end_date.to_s.to_date %> </span>
     </div>
     <div class="col-1 mark-complete d-flex justify-content-center">
      <%= link_to  task_complete_path(task_id: task.id),remote: true,method: :put, data: { confirm: "¿Estas seguro de Completar la Tarea:a: #{task.title}?"} do %>
                  <i class="fa-solid fa-check" data-complete-task="<%=task.id%>"></i>
                <% end %>
     </div>
     <div class="col-1 importance d-flex justify-content-center">
      <span> <%=task.importance%> </span>
    </div>
     <div class="col-3">
      <span> <%= task.title%> </span>
     </div>
     <div class="col-3 col-de-etiquetas" style="font-size:10px; font-weigth:700;">
       <div class="row">
        <div class="col-3" style="background-color:<%=task.labelleds.first.tag.present? ? task.labelleds.first.tag.color : "gray"%>; height:16px">
          <%# Refactorizar1 %>
          <%if task.labelleds.first.tag_id.present? && task.labelleds.first.tag.title.present? %>
            <%= link_to "#{task.labelleds.first.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.second.tag.present? ? task.labelleds.second.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.second.tag_id.present?%>
            <%= link_to "#{task.labelleds.second.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.third.tag.present? ? task.labelleds.third.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.third.tag_id.present?%>
            <%= link_to "#{task.labelleds.third.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3">
          <% label = task.labelleds.third%>
            <%= link_to  edit_labelleds_path(task_id: task.id), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-tags" data-task="<%=task.id%>" ></i>
                <% end %>
        </div>
       </div>
     </div>
     <div class="col-2">
      <%= link_to edit_task_path(task), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
      <%= link_to task, remote: true, method: :delete, data: { confirm: "¿Estas segurode borrar la Tarea: #{task.title}?"}, class: "btn btn-xs"  do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
     </div>

    </div>
  </li>
  <% end %>

  </ul>
</div>

<div class="row container">
  <h3>Mis Tareas Terminadas</h3>
</div>
<div class="container list-tasks">
  <ul id="tasks-lists" class="tasks-lists-complete">
    <li id="task-id">
      <div class="row">
      <div class="col-1">
        <a >
          Inicio
        </a>
      </div>
      <div class="col-1">
        <a >
          Fin
        </a>
      </div>
      <div class="col-1">
        <a >
          Terminar
        </a>
      </div>
      <div class="col-1">
        <a >
          Importancia
        </a>
      </div>
      <div class="col-3">
        <span> Titulo</span>
      </div>
      <div class="col-3 d-flex justify-content-center">
        Etiquetas
      </div>
      <div class="col-2">

        <span>Editar/Eliminar</span>
      </div>
      </div>
    </li>
  <%@tasks_completed.each do |task|%>
  <li id="task-<%=task.id%>" class="task-iterated">
    <div class="row">
     <div class="col-1 text-date">
      <span> <%=task.start_date.to_s.to_date%> </span>
     </div>
     <div class="col-1 text-date">
      <span> <%=task.end_date.to_s.to_date %> </span>
     </div>
     <div class="col-1 mark-complete d-flex justify-content-center">
      <%= link_to  task_complete_path(task_id: task.id),remote: true,method: :put, data: { confirm: "¿Estas seguro de marcar como Pendinete la Tarea: #{task.title}?"} do %>
                  <i class="fa-solid fa-check" data-complete-task="<%=task.id%>"></i>
                <% end %>
     </div>
     <div class="col-1 importance d-flex justify-content-center">
      <span> <%=task.importance%> </span>
    </div>
     <div class="col-3">
      <span> <%= task.title%> </span>
     </div>
     <div class="col-3 col-de-etiquetas" style="font-size:10px; font-weigth:700;">
       <div class="row">
        <div class="col-3" style="background-color:<%=task.labelleds.first.tag.present? ? task.labelleds.first.tag.color : "gray"%>; height:16px">
          <%# Refactorizar1 %>
          <%if task.labelleds.first.tag_id.present? && task.labelleds.first.tag.title.present? %>
            <%= link_to "#{task.labelleds.first.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.second.tag.present? ? task.labelleds.second.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.second.tag_id.present?%>
            <%= link_to "#{task.labelleds.second.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3" style="background-color:<%=task.labelleds.third.tag.present? ? task.labelleds.third.tag.color : "gray"%>; height:16px">
          <%if task.labelleds.third.tag_id.present?%>
            <%= link_to "#{task.labelleds.third.tag.title} ",tasks_path(tag_id: task.labelleds.first.tag.id ) %>
          <% else %>
            -
          <% end %>
        </div>
        <div class="col-3">
          <% label = task.labelleds.third%>
            <%= link_to  edit_labelleds_path(task_id: task.id), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-tags" data-task="<%=task.id%>" ></i>
                <% end %>
        </div>
       </div>
     </div>
     <div class="col-2">
      <%= link_to edit_task_path(task), html_options = {class: "btn  btn-xs", remote: true, style: "color: black"} do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
      <%= link_to task, remote: true, method: :delete, data: { confirm: "¿Estas seguro de borrar la Tarea:a: #{task.title}?"}, class: "btn btn-xs"  do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
     </div>

    </div>
  </li>
  <% end %>

  </ul>
</div>